"""crear entidades iniciales

Revision ID: 3f84bb494760
Revises: 1494b60d30a9
Create Date: 2026-05-11 17:17:41.392274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f84bb494760'
down_revision: Union[str, None] = '1494b60d30a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estrategia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('tipo_activo', sa.String(length=50), nullable=False),
    sa.Column('nivel_riesgo', sa.Integer(), nullable=False),
    sa.Column('precio_subscripcion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comision_ganancias', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'pausada', name='estado_estrategia'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ult_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retorno_total', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volatilidad', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('num_operaciones', sa.Integer(), nullable=True),
    sa.Column('mejor_1m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('peor_1m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mejor_3m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('peor_3m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mejor_1a', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('peor_1a', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.CheckConstraint('nivel_riesgo >= 1 AND nivel_riesgo <= 7', name='ck_estrategia_nivel_riesgo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estrategia_categoria'), 'estrategia', ['categoria'], unique=False)
    op.create_index(op.f('ix_estrategia_estado'), 'estrategia', ['estado'], unique=False)
    op.create_index(op.f('ix_estrategia_nombre'), 'estrategia', ['nombre'], unique=True)
    op.create_index(op.f('ix_estrategia_tipo_activo'), 'estrategia', ['tipo_activo'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'user', name='rol_usuario'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_table('contratacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_estrategia', sa.Integer(), nullable=False),
    sa.Column('fecha_contratacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cancelacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'cancelada', name='estado_contratacion'), nullable=False),
    sa.ForeignKeyConstraint(['id_estrategia'], ['estrategia.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratacion_estado'), 'contratacion', ['estado'], unique=False)
    op.create_index(op.f('ix_contratacion_id_estrategia'), 'contratacion', ['id_estrategia'], unique=False)
    op.create_index(op.f('ix_contratacion_id_usuario'), 'contratacion', ['id_usuario'], unique=False)
    op.create_table('resultado_estrategia',
    sa.Column('id_estrategia', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('retorno', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['id_estrategia'], ['estrategia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_estrategia', 'fecha', name='pk_resultado_estrategia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_estrategia')
    op.drop_index(op.f('ix_contratacion_id_usuario'), table_name='contratacion')
    op.drop_index(op.f('ix_contratacion_id_estrategia'), table_name='contratacion')
    op.drop_index(op.f('ix_contratacion_estado'), table_name='contratacion')
    op.drop_table('contratacion')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_estrategia_tipo_activo'), table_name='estrategia')
    op.drop_index(op.f('ix_estrategia_nombre'), table_name='estrategia')
    op.drop_index(op.f('ix_estrategia_estado'), table_name='estrategia')
    op.drop_index(op.f('ix_estrategia_categoria'), table_name='estrategia')
    op.drop_table('estrategia')
    sa.Enum(name='estado_contratacion').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='rol_usuario').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='estado_estrategia').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
