"""add_saldo_monedero_soft_delete_estado_contratacion

Revision ID: bc3f4b90342a
Revises: 3f84bb494760
Create Date: 2026-05-12 18:17:23.600594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3f4b90342a'
down_revision: Union[str, None] = '3f84bb494760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratacion', sa.Column('monto_invertido', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('estrategia', sa.Column('activa', sa.Boolean(), nullable=False))
    op.add_column('usuario', sa.Column('saldo_monedero', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text("10000.00"),),)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'saldo_monedero')
    op.drop_column('estrategia', 'activa')
    op.drop_column('contratacion', 'monto_invertido')
    # ### end Alembic commands ###
